# Generated by Django 3.0.5 on 2020-04-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='category_id',
            new_name='category',
        ),
    ]
