import { Product } from './product';
/*
  id: number ;
  category_id: number;
  name: string;
  price: string;
  description: string;
  image: string;
  link: string;
 */
export const PRODUCTS: Product[] = [
  //// Flowers
  { id: 10,
    category_id: 1,
    name: 'Geo Fiore',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 4000,
    rating: 5,
    description: 'Магазин цветов',
    image: ''
  },
  { id: 11,
    category_id: 1,
    name: 'Rouge',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 4000,
    rating: 5,
    description: 'Магазин цветов',
    image: ''
  },
  { id: 12,
    category_id: 1,
    name: 'Zakazbuketov',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 4000,
    rating: 5,
    description: 'Магазин цветов',
    image: ''
  },
  { id: 13,
    category_id: 1,
    name: 'Цветок Короля Артура',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 4000,
    rating: 5,
    description: 'Магазин цветов',
    image: ''
  },
  { id: 14,
    category_id: 1,
    name: 'Rafale',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 4000,
    rating: 5,
    description: 'Магазин цветов',
    image: ''
  },
  { id: 15,
    category_id: 1,
    name: 'Империя цветов',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 4000,
    rating: 5,
    description: 'Магазин цветов',
    image: ''
  },
  { id: 16,
    category_id: 1,
    name: 'Счастье Цветочный Магазин',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 4000,
    rating: 5,
    description: 'Магазин цветов',
    image: ''
  },
  { id: 17,
    category_id: 1,
    name: 'Koktem',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 4000,
    rating: 5,
    description: 'Магазин цветов',
    image: ''
  },
  { id: 18,
    category_id: 1,
    name: 'florigi.com',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 3825,
    rating: 5,
    description: 'Магазин цветов',
    image: ''
  },
  { id: 19,
    category_id: 1,
    name: 'Rosalie Flowers',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 4000,
    rating: 4.5,
    description: 'Магазин цветов',
    image: ''
  },
  //// Pizza
  { id: 20,
    category_id: 2,
    name: 'Чибо Сано',
    delivery_time: 90,
    delivery_cost: 400,
    min_order : 0,
    rating: 5,
    description: 'Пиццерия',
    image: ''
  },
  { id: 21,
    category_id: 2,
    name: 'Pomodoro Royal',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Ресторан',
    image: ''
  },
  { id: 22,
    category_id: 2,
    name: 'Sabirkin Kitchen',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 23,
    category_id: 2,
    name: 'Dolcetto',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Ресторан',
    image: ''
  },
  { id: 24,
    category_id: 2,
    name: 'ALFA',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Ресторан',
    image: ''
  },
  { id: 25,
    category_id: 2,
    name: 'Центр плова OD',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 3000,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 26,
    category_id: 2,
    name: 'Domingo',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Служба доставки',
    image: ''
  },
  { id: 27,
    category_id: 2,
    name: 'Sadu',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2000,
    rating: 5,
    description: 'Ресторан',
    image: ''
  },
  { id: 28,
    category_id: 2,
    name: 'La Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 29,
    category_id: 2,
    name: 'Chad',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 30,
    category_id: 3,
    name: 'Чибо Сано',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 4.5,
    description: 'Пиццерия',
    image: ''
  },
  { id: 31,
    category_id: 3,
    name: 'Hokku Sushi',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Суши-бар',
    image: ''
  },
  { id: 32,
    category_id: 3,
    name: 'Chepil',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 33,
    category_id: 3,
    name: 'Sushi & Roll\'s',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Суши-бар',
    image: ''
  },
  { id: 34,
    category_id: 3,
    name: 'Beta Pizza',
    delivery_time: 90,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Служба доставки',
    image: ''
  },
  { id: 35,
    category_id: 3,
    name: 'Тануки',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 4.5,
    description: 'Ресторан',
    image: ''
  },
  { id: 36,
    category_id: 3,
    name: 'Takara Sushi Bar',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 4.5,
    description: 'Ресторан',
    image: ''
  },
  { id: 37,
    category_id: 3,
    name: 'Sushiwok',
    delivery_time: 60,
    delivery_cost: 0,
    min_order : 2500,
    rating: 4.5,
    description: 'Служба доставки',
    image: ''
  },
  { id: 38,
    category_id: 3,
    name: 'Алые Паруса',
    delivery_time: 180,
    delivery_cost: 600,
    min_order : 3000,
    rating: 4.5,
    description: 'Суши-бар',
    image: ''
  },
  { id: 39,
    category_id: 3,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 4.5,
    description: 'Служба доставки',
    image: ''
  },
  { id: 40,
    category_id: 4,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 41,
    category_id: 4,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 42,
    category_id: 4,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 43,
    category_id: 4,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 44,
    category_id: 4,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 45,
    category_id: 4,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 46,
    category_id: 4,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 47,
    category_id: 4,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 48,
    category_id: 4,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },
  { id: 49,
    category_id: 4,
    name: 'Mio Pizza',
    delivery_time: 60,
    delivery_cost: 600,
    min_order : 2500,
    rating: 5,
    description: 'Кафе',
    image: ''
  },






];
